## Generate Test Recordings

Generate test raw recording data and associated time stamps

In [1]:
import os
import math
import struct
import datetime
import pytz
import numpy as np

In [8]:
def ntp_to_datetime(ts):  
    """ Convert Internet Network Time Protocol (NTP) 64bit timestamp into python datetime """
    seconds = int(ts) >> 32
    microseconds = np.bitwise_and(ts, np.uint64(0xFFFFFFFF)) / 2**32
    return datetime.timedelta(seconds=seconds+microseconds) + datetime.datetime(1900, 1, 1, 0, 0, 0, 0, pytz.utc)

def datetime_to_ntp(ts):
    """ Convert python datetime into an Internet Network Time Protocol (NTP) 64bit timestamp """
    diff = ts - datetime.datetime(1900, 1, 1, 0, 0, 0, 0, pytz.utc)
    return np.uint64((int(diff.total_seconds()) << 32) + (diff.microseconds / 1000000 * 2**32))

# Test round trip from python to NTP to python timestamps
datetime_ts = datetime.datetime(2019, 2, 5, 19, 38, 42, 314159, datetime.timezone(-datetime.timedelta(hours=8)))
print(datetime_ts.isoformat())

ntp_ts = datetime_to_ntp(datetime_ts)
print(bin(ntp_ts))

print(ntp_to_datetime(ntp_ts).isoformat())

2019-02-05T19:38:42.314159-08:00
0b1110000000000100110101010100001001010000011011001011100000000000
2019-02-06T03:38:42.314159+00:00


In [2]:
# 1.5 minutes, 4 channels @ 1Hz sample rate
X = np.array([range(i*10, i*10+4) for i in range(60 + 30)], dtype=np.int16)
print(X.shape)

(90, 4)


In [143]:
# Write out two blocks, one a second long and one a half second
with open("derived/test-datasets/experiment_190205_193842.bin", "wb") as f:
    ts = datetime.datetime(2019, 2, 5, 19, 38, 42, 314159, datetime.timezone(-datetime.timedelta(hours=8)))
    print(ts.isoformat())
    f.write(struct.pack('Q', datetime_to_ntp(ts)))
    print(bin(datetime_to_ntp(ts)))
    print(datetime_to_ntp(ts))
    X[0:60,:].astype('int16').tofile(f)
    print(X[0:60,:].astype('int16'))

with open("derived/test-datasets/experiment_190205_193942.bin", "wb") as f:
    ts = datetime.datetime(2019, 2, 5, 19, 39, 42, 314159, datetime.timezone(-datetime.timedelta(hours=8)))
    print(ts.isoformat())
    f.write(struct.pack('Q', datetime_to_ntp(ts)))
    print(bin(datetime_to_ntp(ts)))
    X[60:,:].astype('int16').tofile(f) 
    print(X[60:,:].astype('int16'))

2019-02-05T19:38:42.314159-08:00
0b1110000000000100110101010100001001010000011011001011100000000000
16142261445196560384
[[  0   1   2   3]
 [ 10  11  12  13]
 [ 20  21  22  23]
 [ 30  31  32  33]
 [ 40  41  42  43]
 [ 50  51  52  53]
 [ 60  61  62  63]
 [ 70  71  72  73]
 [ 80  81  82  83]
 [ 90  91  92  93]
 [100 101 102 103]
 [110 111 112 113]
 [120 121 122 123]
 [130 131 132 133]
 [140 141 142 143]
 [150 151 152 153]
 [160 161 162 163]
 [170 171 172 173]
 [180 181 182 183]
 [190 191 192 193]
 [200 201 202 203]
 [210 211 212 213]
 [220 221 222 223]
 [230 231 232 233]
 [240 241 242 243]
 [250 251 252 253]
 [260 261 262 263]
 [270 271 272 273]
 [280 281 282 283]
 [290 291 292 293]
 [300 301 302 303]
 [310 311 312 313]
 [320 321 322 323]
 [330 331 332 333]
 [340 341 342 343]
 [350 351 352 353]
 [360 361 362 363]
 [370 371 372 373]
 [380 381 382 383]
 [390 391 392 393]
 [400 401 402 403]
 [410 411 412 413]
 [420 421 422 423]
 [430 431 432 433]
 [440 441 442 443]
 [450 451 452 453]
 [460

In [11]:
with open("derived/test-datasets/experiment_190205_193842.bin", "rb") as f:
    ts = int(np.fromfile(f, dtype=np.uint64, count=1)[0])
    raw = np.fromfile(f, dtype=np.int16)

num_channels = 4

ntp_to_datetime(ts).isoformat()
print(raw.reshape(-1, num_channels, order="C"))

[[  0   1   2   3]
 [ 10  11  12  13]
 [ 20  21  22  23]
 [ 30  31  32  33]
 [ 40  41  42  43]
 [ 50  51  52  53]
 [ 60  61  62  63]
 [ 70  71  72  73]
 [ 80  81  82  83]
 [ 90  91  92  93]
 [100 101 102 103]
 [110 111 112 113]
 [120 121 122 123]
 [130 131 132 133]
 [140 141 142 143]
 [150 151 152 153]
 [160 161 162 163]
 [170 171 172 173]
 [180 181 182 183]
 [190 191 192 193]
 [200 201 202 203]
 [210 211 212 213]
 [220 221 222 223]
 [230 231 232 233]
 [240 241 242 243]
 [250 251 252 253]
 [260 261 262 263]
 [270 271 272 273]
 [280 281 282 283]
 [290 291 292 293]
 [300 301 302 303]
 [310 311 312 313]
 [320 321 322 323]
 [330 331 332 333]
 [340 341 342 343]
 [350 351 352 353]
 [360 361 362 363]
 [370 371 372 373]
 [380 381 382 383]
 [390 391 392 393]
 [400 401 402 403]
 [410 411 412 413]
 [420 421 422 423]
 [430 431 432 433]
 [440 441 442 443]
 [450 451 452 453]
 [460 461 462 463]
 [470 471 472 473]
 [480 481 482 483]
 [490 491 492 493]
 [500 501 502 503]
 [510 511 512 513]
 [520 521 52