In [107]:
import os
import struct
import datetime
import pytz
import numpy as np

In [85]:
# 1.5 minutes, 4 channels @ 1Hz sample rate
X = np.array([range(i*10, i*10+4) for i in range(60 + 30)], dtype=np.int16)
print(X.shape)

(90, 4)


In [98]:
def datetime_to_ntp(ts):
    """ Convert python datetime into Internet Network Time Protocol (NTP) 64bit timestamp """
    diff = ts - datetime.datetime(1900, 1, 1, 0, 0, 0, 0, pytz.utc)
    return np.uint64(((diff.days*24*60*60 + diff.seconds) << 32) + ts.microsecond // 2**32)

In [105]:
with open("derived/test/experiment_190205_193842.bin", "wb") as f:
    ts = datetime.datetime(2019, 2, 5, 19, 38, 42, 314159, datetime.timezone(-datetime.timedelta(hours=8)))
    print(ts.isoformat())
    f.write(struct.pack('Q', datetime_to_ntp(ts)))
    X[0:60,:].astype('int16').tofile(f)
    print(X[0:60,:].astype('int16'))

with open("derived/test/experiment_190205_193942.bin", "wb") as f:
    ts = datetime.datetime(2019, 2, 5, 19, 39, 42, 314159, datetime.timezone(-datetime.timedelta(hours=8)))
    print(ts.isoformat())
    f.write(struct.pack('Q', ts_ntp))
    X[60:,:].astype('int16').tofile(f) 
    print(X[60:,:].astype('int16'))

2019-02-05T19:38:42.314159-08:00
[[  0   1   2   3]
 [ 10  11  12  13]
 [ 20  21  22  23]
 [ 30  31  32  33]
 [ 40  41  42  43]
 [ 50  51  52  53]
 [ 60  61  62  63]
 [ 70  71  72  73]
 [ 80  81  82  83]
 [ 90  91  92  93]
 [100 101 102 103]
 [110 111 112 113]
 [120 121 122 123]
 [130 131 132 133]
 [140 141 142 143]
 [150 151 152 153]
 [160 161 162 163]
 [170 171 172 173]
 [180 181 182 183]
 [190 191 192 193]
 [200 201 202 203]
 [210 211 212 213]
 [220 221 222 223]
 [230 231 232 233]
 [240 241 242 243]
 [250 251 252 253]
 [260 261 262 263]
 [270 271 272 273]
 [280 281 282 283]
 [290 291 292 293]
 [300 301 302 303]
 [310 311 312 313]
 [320 321 322 323]
 [330 331 332 333]
 [340 341 342 343]
 [350 351 352 353]
 [360 361 362 363]
 [370 371 372 373]
 [380 381 382 383]
 [390 391 392 393]
 [400 401 402 403]
 [410 411 412 413]
 [420 421 422 423]
 [430 431 432 433]
 [440 441 442 443]
 [450 451 452 453]
 [460 461 462 463]
 [470 471 472 473]
 [480 481 482 483]
 [490 491 492 493]
 [500 501 502 503

In [128]:
with open("derived/test/experiment_190205_193842.bin", "rb") as f:
    f.seek(8, os.SEEK_SET)
    raw = np.fromfile(f, dtype=np.int16)
    
raw.gi


array([[  0,   1,   2,   3],
       [ 10,  11,  12,  13],
       [ 20,  21,  22,  23],
       [ 30,  31,  32,  33],
       [ 40,  41,  42,  43],
       [ 50,  51,  52,  53],
       [ 60,  61,  62,  63],
       [ 70,  71,  72,  73],
       [ 80,  81,  82,  83],
       [ 90,  91,  92,  93],
       [100, 101, 102, 103],
       [110, 111, 112, 113],
       [120, 121, 122, 123],
       [130, 131, 132, 133],
       [140, 141, 142, 143],
       [150, 151, 152, 153],
       [160, 161, 162, 163],
       [170, 171, 172, 173],
       [180, 181, 182, 183],
       [190, 191, 192, 193],
       [200, 201, 202, 203],
       [210, 211, 212, 213],
       [220, 221, 222, 223],
       [230, 231, 232, 233],
       [240, 241, 242, 243],
       [250, 251, 252, 253],
       [260, 261, 262, 263],
       [270, 271, 272, 273],
       [280, 281, 282, 283],
       [290, 291, 292, 293],
       [300, 301, 302, 303],
       [310, 311, 312, 313],
       [320, 321, 322, 323],
       [330, 331, 332, 333],
       [340, 3

In [85]:
X = np.load("/tf/braingeneerspy/tests/derived/test/OganoidTest1_190205_193842.npy")
X = X[0:4,:].T
print("Shape", X.shape)
print(X[0:8])

ts = datetime.datetime.strptime("190205_193842", "%y%m%d_%H%M%S").astimezone(pytz.timezone("US/Pacific")))
print("ISO Timestamp", ts.isoformat())
print("Timestamp Seconds", int(ts.timestamp()))

with open("/tf/braingeneerspy/tests/derived/test/experiment_190205_193842.bin", "wb") as f:
    f.write(struct.pack('i', int(ts.timestamp())))
    f.write(struct.pack('i', 0))
    X.astype('int16').tofile(f)    

Shape (1200240, 4)
[[32756 32744 32743 32764]
 [32750 32765 32759 32747]
 [32757 32744 32760 32756]
 [32779 32757 32756 32753]
 [32756 32743 32741 32764]
 [32756 32743 32760 32764]
 [32756 32744 32768 32753]
 [32757 32757 32760 32764]]
ISO Timestamp 2019-02-05T11:38:42-08:00
Timestamp Seconds 1549395522


In [84]:
X = np.load("/tf/braingeneerspy/tests/derived/test/OganoidTest1_190205_193942.npy")
X = X[0:4,:].T
print("Shape", X.shape)
print(X[0:8])

ts = datetime.datetime.strptime("190205_193942", "%y%m%d_%H%M%S").astimezone(pytz.timezone("America/Los_Angeles"))
print("ISO Timestamp", ts.isoformat())
print("Timestamp Seconds", int(ts.timestamp()))

with open("/tf/braingeneerspy/tests/derived/test/experiment_190205_193942.bin", "wb") as f:
    f.write(struct.pack('i', int(ts.timestamp())))
    f.write(struct.pack('i', 0))
    X.astype('int16').tofile(f)    

Shape (1094400, 4)
[[32742 32742 32760 32773]
 [32771 32763 32765 32764]
 [32779 32766 32765 32760]
 [32758 32754 32760 32759]
 [32769 32763 32781 32765]
 [32758 32763 32765 32764]
 [32751 32764 32765 32766]
 [32773 32754 32760 32763]]
ISO Timestamp 2019-02-05T11:39:42-08:00
Timestamp Seconds 1549395582


In [ ]:
file_name = ("/public/groups/braingeneers/staging/original/" +
             "Tetrodes_Headstages_512_Channels_int16_2019-06-26_19-42-12.bin")

# file_name = ("/public/groups/braingeneers/staging/original/" +
#              "Silicon_EAB40_Headstages_256_Channels_int16_2019-04-02_11-49-53.bin")


# file_name = ("/public/groups/braingeneers/staging/original/" +
#              "Silicon_EAB40_Headstages_256_Channels_int16_2019-04-02_11-49-53.bin")

with open(file_name, "rb") as f:
    tr = np.fromfile(f, dtype=np.uint64, count=1)
print(tr)

import datetime
datetime.datetime.fromtimestamp(tr // 1000000)


def to_seconds(h):
    return (h>>32) + ((float)(h&0xffffffff))/pow(2,32)

import time
time.ctime(to_seconds(tr))

raw = np.fromfile(
    "/public/groups/braingeneers/staging/original/Carbon_EAB27_Headstages_64_Channels_int16_2018-12-28_14-55-21.bin",
    dtype=np.int16)



with open(file_name, "rb") as f:
    f.seek(8, os.SEEK_SET)
    raw = np.fromfile(f, dtype=np.int16)
    
gain = np.float64(0.19073486328125) # AKA scaler

number_of_channels = 64
    
length = np.int64(np.size(raw) / number_of_channels)
X = np.reshape(raw, [number_of_channels, length], order='F') * gain
 
print("Shape", X.shape)

plt.figure(figsize=(15,5))
plt.plot(X[8, 0:128])
plt.show()

# num_channels = 16
# plt.figure(figsize=(15, num_channels))
# plt.yticks([])
# plt.xticks([])
# for i in range(num_channels):
#     plt.plot(X[0:128, i] + i*2)

# plt.show()


for i in range(0, 64, 4):
    plt.figure(figsize=(15,5))
    plt.plot(X[i, 0:256])
    plt.show()

    
num_channels = 32
plt.figure(figsize=(15, num_channels))
plt.yticks([])
plt.xticks([])
for i in range(num_channels):
    plt.plot(X[0:128, i] + i*2)

plt.show()